# Generated by Django 5.1.2 on 2024-11-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='color',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pot',
            name='name',
            field=models.CharField(default='yellow', max_length=100),
            preserve_default=False,
        ),
    ]
